#ifndef PIT_H
#define PIT_H

#define ARDUINO 100

#define INCLUDE_vTaskDelete 1

#define SERIAL_RATE 250000U

#define BUTTON_PIN 2
#define RELAY_PIN 4
#define ONE_WIRE_PIN 10

#define ROTARY_ENCODER_A_PIN 32
#define ROTARY_ENCODER_B_PIN 21

#define SHORT_PRESS_DURATION 100
#define LONG_PRESS_DURATION 1000
#define NUISANCE_PRESS_DURATION 10000

#define BUTTON_READ_BLOCK_DURATION 1000/30

#define BRINGUP_CODE 0xCFB3

#define SECONDS_IN_DAY 86400ULL
#define SECONDS_IN_HOUR 3600ULL
#define SECONDS_IN_MINUTE 60ULL

#define TIMER_MODE 0
#define THERMOSTAT_MODE 1

typedef char RUN_MODE;

#endif //PIT_H